export const networkIdMap = new Map<number, string>()
  .set(11, 'https://nebunet-gateway.radixdlt.com')
  .set(32, 'https://gilganet-gateway.radixdlt.com')
  .set(33, 'https://enkinet-gateway.radixdlt.com')
  .set(34, 'https://hammunet-gateway.radixdlt.com')
